services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=poemes'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mount init.sql only if you need to initialize the database
      # - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
    name: poemes_postgres_data # Named volume for easier identification
